### ISSUE TITLE
Progress bar does not disappear when Set-SCPFile completes

### ISSUE THREAD

**Issue by mdinicola** [darkoperator/Posh-SSH#14]
When I use the Set-SCPFile cmdlet, the progress bar will stay displayed until the entire script exits.

I am performing operations after uploading the file has completed, and it is somewhat annoying for the progress bar to stay on the screen the whole time.  I think it should disappear when the upload has been completed.

**Comment by darkoperator** [comment]
Will have it fixed in the next release that is being finalized.

**Comment by darkoperator** [comment]
Please test release 1.7 pushed out today.

**Comment by mdinicola** [comment]
I tested this with 1.7.2, and the issue is still there.  The progress bar still says on the screen until the entire script has exited.

**Comment by darkoperator** [comment]
can you give me more info on the target OS, version of SSH and file size you are uploading? I have not been able to replicate

**Comment by carlos-l** [comment]
When using Set-SFPFile with Powershell ISE I can see the same issue. 

The issue was only producible when using PowerShell ISE. I have not been able to re-create it using a standard prompt so its a no issue for me. 
##### Screen shot:
![screen shot 2016-02-02 at 4 35 12 pm](https://cloud.githubusercontent.com/assets/1732243/12742645/fb962e6e-c9ca-11e5-8054-44b38b9a00cc.png)
##### Version
|Name | Value|
|----|-----|
PSVersion | 5.0.10586.0
PSCompatibleVersions | {1.0, 2.0, 3.0, 4.0...}
BuildVersion | 10.0.10586.0
CLRVersion | 4.0.30319.42000
WSManStackVersion | 3.0
PSRemotingProtocolVersion | 2.3
SerializationVersion | 1.1.0.1
Operating System | Windows 10 x64 US-EN
Posh-SSH | 1.7.3

Thank you providing this tool. Its been a great help.

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery added an option to not show a progress bar.

**Comment by darkoperator** [comment]
closing issue, can re-open if needed.
